// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: chirp_000000e1.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "chirp_000000e1.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace chirp_000000e1_ns {

namespace {

const ::google::protobuf::Descriptor* ScatterMessage_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  ScatterMessage_reflection_ = NULL;
const ::google::protobuf::Descriptor* GatherMessage_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  GatherMessage_reflection_ = NULL;
const ::google::protobuf::Descriptor* GatherMessage_Pair_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  GatherMessage_Pair_reflection_ = NULL;
const ::google::protobuf::Descriptor* PublishMessage_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  PublishMessage_reflection_ = NULL;
const ::google::protobuf::Descriptor* PublishMessage_Pair_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  PublishMessage_Pair_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_chirp_5f000000e1_2eproto() {
  protobuf_AddDesc_chirp_5f000000e1_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "chirp_000000e1.proto");
  GOOGLE_CHECK(file != NULL);
  ScatterMessage_descriptor_ = file->message_type(0);
  static const int ScatterMessage_offsets_[1] = {
  };
  ScatterMessage_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      ScatterMessage_descriptor_,
      ScatterMessage::default_instance_,
      ScatterMessage_offsets_,
      -1,
      -1,
      -1,
      sizeof(ScatterMessage),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ScatterMessage, _internal_metadata_),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ScatterMessage, _is_default_instance_));
  GatherMessage_descriptor_ = file->message_type(1);
  static const int GatherMessage_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(GatherMessage, value_),
  };
  GatherMessage_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      GatherMessage_descriptor_,
      GatherMessage::default_instance_,
      GatherMessage_offsets_,
      -1,
      -1,
      -1,
      sizeof(GatherMessage),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(GatherMessage, _internal_metadata_),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(GatherMessage, _is_default_instance_));
  GatherMessage_Pair_descriptor_ = GatherMessage_descriptor_->nested_type(0);
  static const int GatherMessage_Pair_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(GatherMessage_Pair, first_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(GatherMessage_Pair, second_),
  };
  GatherMessage_Pair_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      GatherMessage_Pair_descriptor_,
      GatherMessage_Pair::default_instance_,
      GatherMessage_Pair_offsets_,
      -1,
      -1,
      -1,
      sizeof(GatherMessage_Pair),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(GatherMessage_Pair, _internal_metadata_),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(GatherMessage_Pair, _is_default_instance_));
  PublishMessage_descriptor_ = file->message_type(2);
  static const int PublishMessage_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PublishMessage, value_),
  };
  PublishMessage_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      PublishMessage_descriptor_,
      PublishMessage::default_instance_,
      PublishMessage_offsets_,
      -1,
      -1,
      -1,
      sizeof(PublishMessage),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PublishMessage, _internal_metadata_),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PublishMessage, _is_default_instance_));
  PublishMessage_Pair_descriptor_ = PublishMessage_descriptor_->nested_type(0);
  static const int PublishMessage_Pair_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PublishMessage_Pair, first_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PublishMessage_Pair, second_),
  };
  PublishMessage_Pair_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      PublishMessage_Pair_descriptor_,
      PublishMessage_Pair::default_instance_,
      PublishMessage_Pair_offsets_,
      -1,
      -1,
      -1,
      sizeof(PublishMessage_Pair),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PublishMessage_Pair, _internal_metadata_),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PublishMessage_Pair, _is_default_instance_));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_chirp_5f000000e1_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      ScatterMessage_descriptor_, &ScatterMessage::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      GatherMessage_descriptor_, &GatherMessage::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      GatherMessage_Pair_descriptor_, &GatherMessage_Pair::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      PublishMessage_descriptor_, &PublishMessage::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      PublishMessage_Pair_descriptor_, &PublishMessage_Pair::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_chirp_5f000000e1_2eproto() {
  delete ScatterMessage::default_instance_;
  delete ScatterMessage_reflection_;
  delete GatherMessage::default_instance_;
  delete GatherMessage_reflection_;
  delete GatherMessage_Pair::default_instance_;
  delete GatherMessage_Pair_reflection_;
  delete PublishMessage::default_instance_;
  delete PublishMessage_reflection_;
  delete PublishMessage_Pair::default_instance_;
  delete PublishMessage_Pair_reflection_;
}

void protobuf_AddDesc_chirp_5f000000e1_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\024chirp_000000e1.proto\022\016chirp_000000e1\"\020"
    "\n\016ScatterMessage\"i\n\rGatherMessage\0221\n\005val"
    "ue\030\002 \001(\0132\".chirp_000000e1.GatherMessage."
    "Pair\032%\n\004Pair\022\r\n\005first\030\001 \001(\010\022\016\n\006second\030\002 "
    "\001(\021\"k\n\016PublishMessage\0222\n\005value\030\002 \001(\0132#.c"
    "hirp_000000e1.PublishMessage.Pair\032%\n\004Pai"
    "r\022\r\n\005first\030\001 \001(\010\022\016\n\006second\030\002 \001(\021b\006proto3", 280);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "chirp_000000e1.proto", &protobuf_RegisterTypes);
  ScatterMessage::default_instance_ = new ScatterMessage();
  GatherMessage::default_instance_ = new GatherMessage();
  GatherMessage_Pair::default_instance_ = new GatherMessage_Pair();
  PublishMessage::default_instance_ = new PublishMessage();
  PublishMessage_Pair::default_instance_ = new PublishMessage_Pair();
  ScatterMessage::default_instance_->InitAsDefaultInstance();
  GatherMessage::default_instance_->InitAsDefaultInstance();
  GatherMessage_Pair::default_instance_->InitAsDefaultInstance();
  PublishMessage::default_instance_->InitAsDefaultInstance();
  PublishMessage_Pair::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_chirp_5f000000e1_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_chirp_5f000000e1_2eproto {
  StaticDescriptorInitializer_chirp_5f000000e1_2eproto() {
    protobuf_AddDesc_chirp_5f000000e1_2eproto();
  }
} static_descriptor_initializer_chirp_5f000000e1_2eproto_;

namespace {

static void MergeFromFail(int line) GOOGLE_ATTRIBUTE_COLD;
static void MergeFromFail(int line) {
  GOOGLE_CHECK(false) << __FILE__ << ":" << line;
}

}  // namespace


// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

ScatterMessage::ScatterMessage()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:chirp_000000e1_ns.ScatterMessage)
}

void ScatterMessage::InitAsDefaultInstance() {
  _is_default_instance_ = true;
}

ScatterMessage::ScatterMessage(const ScatterMessage& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:chirp_000000e1_ns.ScatterMessage)
}

void ScatterMessage::SharedCtor() {
    _is_default_instance_ = false;
  _cached_size_ = 0;
}

ScatterMessage::~ScatterMessage() {
  // @@protoc_insertion_point(destructor:chirp_000000e1_ns.ScatterMessage)
  SharedDtor();
}

void ScatterMessage::SharedDtor() {
  if (this != default_instance_) {
  }
}

void ScatterMessage::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* ScatterMessage::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return ScatterMessage_descriptor_;
}

const ScatterMessage& ScatterMessage::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_chirp_5f000000e1_2eproto();
  return *default_instance_;
}

ScatterMessage* ScatterMessage::default_instance_ = NULL;

ScatterMessage* ScatterMessage::New(::google::protobuf::Arena* arena) const {
  ScatterMessage* n = new ScatterMessage;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void ScatterMessage::Clear() {
// @@protoc_insertion_point(message_clear_start:chirp_000000e1_ns.ScatterMessage)
}

bool ScatterMessage::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:chirp_000000e1_ns.ScatterMessage)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
  handle_unusual:
    if (tag == 0 ||
        ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
        ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
      goto success;
    }
    DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
  }
success:
  // @@protoc_insertion_point(parse_success:chirp_000000e1_ns.ScatterMessage)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:chirp_000000e1_ns.ScatterMessage)
  return false;
#undef DO_
}

void ScatterMessage::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:chirp_000000e1_ns.ScatterMessage)
  // @@protoc_insertion_point(serialize_end:chirp_000000e1_ns.ScatterMessage)
}

::google::protobuf::uint8* ScatterMessage::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:chirp_000000e1_ns.ScatterMessage)
  // @@protoc_insertion_point(serialize_to_array_end:chirp_000000e1_ns.ScatterMessage)
  return target;
}

int ScatterMessage::ByteSize() const {
// @@protoc_insertion_point(message_byte_size_start:chirp_000000e1_ns.ScatterMessage)
  int total_size = 0;

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void ScatterMessage::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:chirp_000000e1_ns.ScatterMessage)
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  const ScatterMessage* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const ScatterMessage>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:chirp_000000e1_ns.ScatterMessage)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:chirp_000000e1_ns.ScatterMessage)
    MergeFrom(*source);
  }
}

void ScatterMessage::MergeFrom(const ScatterMessage& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:chirp_000000e1_ns.ScatterMessage)
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
}

void ScatterMessage::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:chirp_000000e1_ns.ScatterMessage)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ScatterMessage::CopyFrom(const ScatterMessage& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:chirp_000000e1_ns.ScatterMessage)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ScatterMessage::IsInitialized() const {

  return true;
}

void ScatterMessage::Swap(ScatterMessage* other) {
  if (other == this) return;
  InternalSwap(other);
}
void ScatterMessage::InternalSwap(ScatterMessage* other) {
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata ScatterMessage::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = ScatterMessage_descriptor_;
  metadata.reflection = ScatterMessage_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// ScatterMessage

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int GatherMessage_Pair::kFirstFieldNumber;
const int GatherMessage_Pair::kSecondFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

GatherMessage_Pair::GatherMessage_Pair()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:chirp_000000e1_ns.GatherMessage.Pair)
}

void GatherMessage_Pair::InitAsDefaultInstance() {
  _is_default_instance_ = true;
}

GatherMessage_Pair::GatherMessage_Pair(const GatherMessage_Pair& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:chirp_000000e1_ns.GatherMessage.Pair)
}

void GatherMessage_Pair::SharedCtor() {
    _is_default_instance_ = false;
  _cached_size_ = 0;
  first_ = false;
  second_ = 0;
}

GatherMessage_Pair::~GatherMessage_Pair() {
  // @@protoc_insertion_point(destructor:chirp_000000e1_ns.GatherMessage.Pair)
  SharedDtor();
}

void GatherMessage_Pair::SharedDtor() {
  if (this != default_instance_) {
  }
}

void GatherMessage_Pair::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* GatherMessage_Pair::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return GatherMessage_Pair_descriptor_;
}

const GatherMessage_Pair& GatherMessage_Pair::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_chirp_5f000000e1_2eproto();
  return *default_instance_;
}

GatherMessage_Pair* GatherMessage_Pair::default_instance_ = NULL;

GatherMessage_Pair* GatherMessage_Pair::New(::google::protobuf::Arena* arena) const {
  GatherMessage_Pair* n = new GatherMessage_Pair;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void GatherMessage_Pair::Clear() {
// @@protoc_insertion_point(message_clear_start:chirp_000000e1_ns.GatherMessage.Pair)
#if defined(__clang__)
#define ZR_HELPER_(f) \
  _Pragma("clang diagnostic push") \
  _Pragma("clang diagnostic ignored \"-Winvalid-offsetof\"") \
  __builtin_offsetof(GatherMessage_Pair, f) \
  _Pragma("clang diagnostic pop")
#else
#define ZR_HELPER_(f) reinterpret_cast<char*>(\
  &reinterpret_cast<GatherMessage_Pair*>(16)->f)
#endif

#define ZR_(first, last) do {\
  ::memset(&first, 0,\
           ZR_HELPER_(last) - ZR_HELPER_(first) + sizeof(last));\
} while (0)

  ZR_(first_, second_);

#undef ZR_HELPER_
#undef ZR_

}

bool GatherMessage_Pair::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:chirp_000000e1_ns.GatherMessage.Pair)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional bool first = 1;
      case 1: {
        if (tag == 8) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &first_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(16)) goto parse_second;
        break;
      }

      // optional sint32 second = 2;
      case 2: {
        if (tag == 16) {
         parse_second:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_SINT32>(
                 input, &second_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:chirp_000000e1_ns.GatherMessage.Pair)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:chirp_000000e1_ns.GatherMessage.Pair)
  return false;
#undef DO_
}

void GatherMessage_Pair::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:chirp_000000e1_ns.GatherMessage.Pair)
  // optional bool first = 1;
  if (this->first() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(1, this->first(), output);
  }

  // optional sint32 second = 2;
  if (this->second() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteSInt32(2, this->second(), output);
  }

  // @@protoc_insertion_point(serialize_end:chirp_000000e1_ns.GatherMessage.Pair)
}

::google::protobuf::uint8* GatherMessage_Pair::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:chirp_000000e1_ns.GatherMessage.Pair)
  // optional bool first = 1;
  if (this->first() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(1, this->first(), target);
  }

  // optional sint32 second = 2;
  if (this->second() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteSInt32ToArray(2, this->second(), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:chirp_000000e1_ns.GatherMessage.Pair)
  return target;
}

int GatherMessage_Pair::ByteSize() const {
// @@protoc_insertion_point(message_byte_size_start:chirp_000000e1_ns.GatherMessage.Pair)
  int total_size = 0;

  // optional bool first = 1;
  if (this->first() != 0) {
    total_size += 1 + 1;
  }

  // optional sint32 second = 2;
  if (this->second() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::SInt32Size(
        this->second());
  }

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void GatherMessage_Pair::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:chirp_000000e1_ns.GatherMessage.Pair)
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  const GatherMessage_Pair* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const GatherMessage_Pair>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:chirp_000000e1_ns.GatherMessage.Pair)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:chirp_000000e1_ns.GatherMessage.Pair)
    MergeFrom(*source);
  }
}

void GatherMessage_Pair::MergeFrom(const GatherMessage_Pair& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:chirp_000000e1_ns.GatherMessage.Pair)
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  if (from.first() != 0) {
    set_first(from.first());
  }
  if (from.second() != 0) {
    set_second(from.second());
  }
}

void GatherMessage_Pair::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:chirp_000000e1_ns.GatherMessage.Pair)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void GatherMessage_Pair::CopyFrom(const GatherMessage_Pair& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:chirp_000000e1_ns.GatherMessage.Pair)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool GatherMessage_Pair::IsInitialized() const {

  return true;
}

void GatherMessage_Pair::Swap(GatherMessage_Pair* other) {
  if (other == this) return;
  InternalSwap(other);
}
void GatherMessage_Pair::InternalSwap(GatherMessage_Pair* other) {
  std::swap(first_, other->first_);
  std::swap(second_, other->second_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata GatherMessage_Pair::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = GatherMessage_Pair_descriptor_;
  metadata.reflection = GatherMessage_Pair_reflection_;
  return metadata;
}


// -------------------------------------------------------------------

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int GatherMessage::kValueFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

GatherMessage::GatherMessage()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:chirp_000000e1_ns.GatherMessage)
}

void GatherMessage::InitAsDefaultInstance() {
  _is_default_instance_ = true;
  value_ = const_cast< ::chirp_000000e1_ns::GatherMessage_Pair*>(&::chirp_000000e1_ns::GatherMessage_Pair::default_instance());
}

GatherMessage::GatherMessage(const GatherMessage& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:chirp_000000e1_ns.GatherMessage)
}

void GatherMessage::SharedCtor() {
    _is_default_instance_ = false;
  _cached_size_ = 0;
  value_ = NULL;
}

GatherMessage::~GatherMessage() {
  // @@protoc_insertion_point(destructor:chirp_000000e1_ns.GatherMessage)
  SharedDtor();
}

void GatherMessage::SharedDtor() {
  if (this != default_instance_) {
    delete value_;
  }
}

void GatherMessage::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* GatherMessage::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return GatherMessage_descriptor_;
}

const GatherMessage& GatherMessage::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_chirp_5f000000e1_2eproto();
  return *default_instance_;
}

GatherMessage* GatherMessage::default_instance_ = NULL;

GatherMessage* GatherMessage::New(::google::protobuf::Arena* arena) const {
  GatherMessage* n = new GatherMessage;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void GatherMessage::Clear() {
// @@protoc_insertion_point(message_clear_start:chirp_000000e1_ns.GatherMessage)
  if (GetArenaNoVirtual() == NULL && value_ != NULL) delete value_;
  value_ = NULL;
}

bool GatherMessage::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:chirp_000000e1_ns.GatherMessage)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional .chirp_000000e1.GatherMessage.Pair value = 2;
      case 2: {
        if (tag == 18) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_value()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:chirp_000000e1_ns.GatherMessage)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:chirp_000000e1_ns.GatherMessage)
  return false;
#undef DO_
}

void GatherMessage::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:chirp_000000e1_ns.GatherMessage)
  // optional .chirp_000000e1.GatherMessage.Pair value = 2;
  if (this->has_value()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      2, *this->value_, output);
  }

  // @@protoc_insertion_point(serialize_end:chirp_000000e1_ns.GatherMessage)
}

::google::protobuf::uint8* GatherMessage::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:chirp_000000e1_ns.GatherMessage)
  // optional .chirp_000000e1.GatherMessage.Pair value = 2;
  if (this->has_value()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        2, *this->value_, target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:chirp_000000e1_ns.GatherMessage)
  return target;
}

int GatherMessage::ByteSize() const {
// @@protoc_insertion_point(message_byte_size_start:chirp_000000e1_ns.GatherMessage)
  int total_size = 0;

  // optional .chirp_000000e1.GatherMessage.Pair value = 2;
  if (this->has_value()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        *this->value_);
  }

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void GatherMessage::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:chirp_000000e1_ns.GatherMessage)
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  const GatherMessage* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const GatherMessage>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:chirp_000000e1_ns.GatherMessage)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:chirp_000000e1_ns.GatherMessage)
    MergeFrom(*source);
  }
}

void GatherMessage::MergeFrom(const GatherMessage& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:chirp_000000e1_ns.GatherMessage)
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  if (from.has_value()) {
    mutable_value()->::chirp_000000e1_ns::GatherMessage_Pair::MergeFrom(from.value());
  }
}

void GatherMessage::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:chirp_000000e1_ns.GatherMessage)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void GatherMessage::CopyFrom(const GatherMessage& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:chirp_000000e1_ns.GatherMessage)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool GatherMessage::IsInitialized() const {

  return true;
}

void GatherMessage::Swap(GatherMessage* other) {
  if (other == this) return;
  InternalSwap(other);
}
void GatherMessage::InternalSwap(GatherMessage* other) {
  std::swap(value_, other->value_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata GatherMessage::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = GatherMessage_descriptor_;
  metadata.reflection = GatherMessage_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// GatherMessage_Pair

// optional bool first = 1;
void GatherMessage_Pair::clear_first() {
  first_ = false;
}
 bool GatherMessage_Pair::first() const {
  // @@protoc_insertion_point(field_get:chirp_000000e1_ns.GatherMessage.Pair.first)
  return first_;
}
 void GatherMessage_Pair::set_first(bool value) {
  
  first_ = value;
  // @@protoc_insertion_point(field_set:chirp_000000e1_ns.GatherMessage.Pair.first)
}

// optional sint32 second = 2;
void GatherMessage_Pair::clear_second() {
  second_ = 0;
}
 ::google::protobuf::int32 GatherMessage_Pair::second() const {
  // @@protoc_insertion_point(field_get:chirp_000000e1_ns.GatherMessage.Pair.second)
  return second_;
}
 void GatherMessage_Pair::set_second(::google::protobuf::int32 value) {
  
  second_ = value;
  // @@protoc_insertion_point(field_set:chirp_000000e1_ns.GatherMessage.Pair.second)
}

// -------------------------------------------------------------------

// GatherMessage

// optional .chirp_000000e1.GatherMessage.Pair value = 2;
bool GatherMessage::has_value() const {
  return !_is_default_instance_ && value_ != NULL;
}
void GatherMessage::clear_value() {
  if (GetArenaNoVirtual() == NULL && value_ != NULL) delete value_;
  value_ = NULL;
}
const ::chirp_000000e1_ns::GatherMessage_Pair& GatherMessage::value() const {
  // @@protoc_insertion_point(field_get:chirp_000000e1_ns.GatherMessage.value)
  return value_ != NULL ? *value_ : *default_instance_->value_;
}
::chirp_000000e1_ns::GatherMessage_Pair* GatherMessage::mutable_value() {
  
  if (value_ == NULL) {
    value_ = new ::chirp_000000e1_ns::GatherMessage_Pair;
  }
  // @@protoc_insertion_point(field_mutable:chirp_000000e1_ns.GatherMessage.value)
  return value_;
}
::chirp_000000e1_ns::GatherMessage_Pair* GatherMessage::release_value() {
  // @@protoc_insertion_point(field_release:chirp_000000e1_ns.GatherMessage.value)
  
  ::chirp_000000e1_ns::GatherMessage_Pair* temp = value_;
  value_ = NULL;
  return temp;
}
void GatherMessage::set_allocated_value(::chirp_000000e1_ns::GatherMessage_Pair* value) {
  delete value_;
  value_ = value;
  if (value) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:chirp_000000e1_ns.GatherMessage.value)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int PublishMessage_Pair::kFirstFieldNumber;
const int PublishMessage_Pair::kSecondFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

PublishMessage_Pair::PublishMessage_Pair()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:chirp_000000e1_ns.PublishMessage.Pair)
}

void PublishMessage_Pair::InitAsDefaultInstance() {
  _is_default_instance_ = true;
}

PublishMessage_Pair::PublishMessage_Pair(const PublishMessage_Pair& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:chirp_000000e1_ns.PublishMessage.Pair)
}

void PublishMessage_Pair::SharedCtor() {
    _is_default_instance_ = false;
  _cached_size_ = 0;
  first_ = false;
  second_ = 0;
}

PublishMessage_Pair::~PublishMessage_Pair() {
  // @@protoc_insertion_point(destructor:chirp_000000e1_ns.PublishMessage.Pair)
  SharedDtor();
}

void PublishMessage_Pair::SharedDtor() {
  if (this != default_instance_) {
  }
}

void PublishMessage_Pair::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* PublishMessage_Pair::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return PublishMessage_Pair_descriptor_;
}

const PublishMessage_Pair& PublishMessage_Pair::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_chirp_5f000000e1_2eproto();
  return *default_instance_;
}

PublishMessage_Pair* PublishMessage_Pair::default_instance_ = NULL;

PublishMessage_Pair* PublishMessage_Pair::New(::google::protobuf::Arena* arena) const {
  PublishMessage_Pair* n = new PublishMessage_Pair;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void PublishMessage_Pair::Clear() {
// @@protoc_insertion_point(message_clear_start:chirp_000000e1_ns.PublishMessage.Pair)
#if defined(__clang__)
#define ZR_HELPER_(f) \
  _Pragma("clang diagnostic push") \
  _Pragma("clang diagnostic ignored \"-Winvalid-offsetof\"") \
  __builtin_offsetof(PublishMessage_Pair, f) \
  _Pragma("clang diagnostic pop")
#else
#define ZR_HELPER_(f) reinterpret_cast<char*>(\
  &reinterpret_cast<PublishMessage_Pair*>(16)->f)
#endif

#define ZR_(first, last) do {\
  ::memset(&first, 0,\
           ZR_HELPER_(last) - ZR_HELPER_(first) + sizeof(last));\
} while (0)

  ZR_(first_, second_);

#undef ZR_HELPER_
#undef ZR_

}

bool PublishMessage_Pair::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:chirp_000000e1_ns.PublishMessage.Pair)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional bool first = 1;
      case 1: {
        if (tag == 8) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &first_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(16)) goto parse_second;
        break;
      }

      // optional sint32 second = 2;
      case 2: {
        if (tag == 16) {
         parse_second:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_SINT32>(
                 input, &second_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:chirp_000000e1_ns.PublishMessage.Pair)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:chirp_000000e1_ns.PublishMessage.Pair)
  return false;
#undef DO_
}

void PublishMessage_Pair::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:chirp_000000e1_ns.PublishMessage.Pair)
  // optional bool first = 1;
  if (this->first() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(1, this->first(), output);
  }

  // optional sint32 second = 2;
  if (this->second() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteSInt32(2, this->second(), output);
  }

  // @@protoc_insertion_point(serialize_end:chirp_000000e1_ns.PublishMessage.Pair)
}

::google::protobuf::uint8* PublishMessage_Pair::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:chirp_000000e1_ns.PublishMessage.Pair)
  // optional bool first = 1;
  if (this->first() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(1, this->first(), target);
  }

  // optional sint32 second = 2;
  if (this->second() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteSInt32ToArray(2, this->second(), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:chirp_000000e1_ns.PublishMessage.Pair)
  return target;
}

int PublishMessage_Pair::ByteSize() const {
// @@protoc_insertion_point(message_byte_size_start:chirp_000000e1_ns.PublishMessage.Pair)
  int total_size = 0;

  // optional bool first = 1;
  if (this->first() != 0) {
    total_size += 1 + 1;
  }

  // optional sint32 second = 2;
  if (this->second() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::SInt32Size(
        this->second());
  }

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void PublishMessage_Pair::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:chirp_000000e1_ns.PublishMessage.Pair)
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  const PublishMessage_Pair* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const PublishMessage_Pair>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:chirp_000000e1_ns.PublishMessage.Pair)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:chirp_000000e1_ns.PublishMessage.Pair)
    MergeFrom(*source);
  }
}

void PublishMessage_Pair::MergeFrom(const PublishMessage_Pair& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:chirp_000000e1_ns.PublishMessage.Pair)
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  if (from.first() != 0) {
    set_first(from.first());
  }
  if (from.second() != 0) {
    set_second(from.second());
  }
}

void PublishMessage_Pair::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:chirp_000000e1_ns.PublishMessage.Pair)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void PublishMessage_Pair::CopyFrom(const PublishMessage_Pair& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:chirp_000000e1_ns.PublishMessage.Pair)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool PublishMessage_Pair::IsInitialized() const {

  return true;
}

void PublishMessage_Pair::Swap(PublishMessage_Pair* other) {
  if (other == this) return;
  InternalSwap(other);
}
void PublishMessage_Pair::InternalSwap(PublishMessage_Pair* other) {
  std::swap(first_, other->first_);
  std::swap(second_, other->second_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata PublishMessage_Pair::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = PublishMessage_Pair_descriptor_;
  metadata.reflection = PublishMessage_Pair_reflection_;
  return metadata;
}


// -------------------------------------------------------------------

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int PublishMessage::kValueFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

PublishMessage::PublishMessage()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:chirp_000000e1_ns.PublishMessage)
}

void PublishMessage::InitAsDefaultInstance() {
  _is_default_instance_ = true;
  value_ = const_cast< ::chirp_000000e1_ns::PublishMessage_Pair*>(&::chirp_000000e1_ns::PublishMessage_Pair::default_instance());
}

PublishMessage::PublishMessage(const PublishMessage& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:chirp_000000e1_ns.PublishMessage)
}

void PublishMessage::SharedCtor() {
    _is_default_instance_ = false;
  _cached_size_ = 0;
  value_ = NULL;
}

PublishMessage::~PublishMessage() {
  // @@protoc_insertion_point(destructor:chirp_000000e1_ns.PublishMessage)
  SharedDtor();
}

void PublishMessage::SharedDtor() {
  if (this != default_instance_) {
    delete value_;
  }
}

void PublishMessage::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* PublishMessage::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return PublishMessage_descriptor_;
}

const PublishMessage& PublishMessage::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_chirp_5f000000e1_2eproto();
  return *default_instance_;
}

PublishMessage* PublishMessage::default_instance_ = NULL;

PublishMessage* PublishMessage::New(::google::protobuf::Arena* arena) const {
  PublishMessage* n = new PublishMessage;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void PublishMessage::Clear() {
// @@protoc_insertion_point(message_clear_start:chirp_000000e1_ns.PublishMessage)
  if (GetArenaNoVirtual() == NULL && value_ != NULL) delete value_;
  value_ = NULL;
}

bool PublishMessage::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:chirp_000000e1_ns.PublishMessage)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional .chirp_000000e1.PublishMessage.Pair value = 2;
      case 2: {
        if (tag == 18) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_value()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:chirp_000000e1_ns.PublishMessage)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:chirp_000000e1_ns.PublishMessage)
  return false;
#undef DO_
}

void PublishMessage::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:chirp_000000e1_ns.PublishMessage)
  // optional .chirp_000000e1.PublishMessage.Pair value = 2;
  if (this->has_value()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      2, *this->value_, output);
  }

  // @@protoc_insertion_point(serialize_end:chirp_000000e1_ns.PublishMessage)
}

::google::protobuf::uint8* PublishMessage::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:chirp_000000e1_ns.PublishMessage)
  // optional .chirp_000000e1.PublishMessage.Pair value = 2;
  if (this->has_value()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        2, *this->value_, target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:chirp_000000e1_ns.PublishMessage)
  return target;
}

int PublishMessage::ByteSize() const {
// @@protoc_insertion_point(message_byte_size_start:chirp_000000e1_ns.PublishMessage)
  int total_size = 0;

  // optional .chirp_000000e1.PublishMessage.Pair value = 2;
  if (this->has_value()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        *this->value_);
  }

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void PublishMessage::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:chirp_000000e1_ns.PublishMessage)
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  const PublishMessage* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const PublishMessage>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:chirp_000000e1_ns.PublishMessage)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:chirp_000000e1_ns.PublishMessage)
    MergeFrom(*source);
  }
}

void PublishMessage::MergeFrom(const PublishMessage& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:chirp_000000e1_ns.PublishMessage)
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  if (from.has_value()) {
    mutable_value()->::chirp_000000e1_ns::PublishMessage_Pair::MergeFrom(from.value());
  }
}

void PublishMessage::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:chirp_000000e1_ns.PublishMessage)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void PublishMessage::CopyFrom(const PublishMessage& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:chirp_000000e1_ns.PublishMessage)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool PublishMessage::IsInitialized() const {

  return true;
}

void PublishMessage::Swap(PublishMessage* other) {
  if (other == this) return;
  InternalSwap(other);
}
void PublishMessage::InternalSwap(PublishMessage* other) {
  std::swap(value_, other->value_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata PublishMessage::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = PublishMessage_descriptor_;
  metadata.reflection = PublishMessage_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// PublishMessage_Pair

// optional bool first = 1;
void PublishMessage_Pair::clear_first() {
  first_ = false;
}
 bool PublishMessage_Pair::first() const {
  // @@protoc_insertion_point(field_get:chirp_000000e1_ns.PublishMessage.Pair.first)
  return first_;
}
 void PublishMessage_Pair::set_first(bool value) {
  
  first_ = value;
  // @@protoc_insertion_point(field_set:chirp_000000e1_ns.PublishMessage.Pair.first)
}

// optional sint32 second = 2;
void PublishMessage_Pair::clear_second() {
  second_ = 0;
}
 ::google::protobuf::int32 PublishMessage_Pair::second() const {
  // @@protoc_insertion_point(field_get:chirp_000000e1_ns.PublishMessage.Pair.second)
  return second_;
}
 void PublishMessage_Pair::set_second(::google::protobuf::int32 value) {
  
  second_ = value;
  // @@protoc_insertion_point(field_set:chirp_000000e1_ns.PublishMessage.Pair.second)
}

// -------------------------------------------------------------------

// PublishMessage

// optional .chirp_000000e1.PublishMessage.Pair value = 2;
bool PublishMessage::has_value() const {
  return !_is_default_instance_ && value_ != NULL;
}
void PublishMessage::clear_value() {
  if (GetArenaNoVirtual() == NULL && value_ != NULL) delete value_;
  value_ = NULL;
}
const ::chirp_000000e1_ns::PublishMessage_Pair& PublishMessage::value() const {
  // @@protoc_insertion_point(field_get:chirp_000000e1_ns.PublishMessage.value)
  return value_ != NULL ? *value_ : *default_instance_->value_;
}
::chirp_000000e1_ns::PublishMessage_Pair* PublishMessage::mutable_value() {
  
  if (value_ == NULL) {
    value_ = new ::chirp_000000e1_ns::PublishMessage_Pair;
  }
  // @@protoc_insertion_point(field_mutable:chirp_000000e1_ns.PublishMessage.value)
  return value_;
}
::chirp_000000e1_ns::PublishMessage_Pair* PublishMessage::release_value() {
  // @@protoc_insertion_point(field_release:chirp_000000e1_ns.PublishMessage.value)
  
  ::chirp_000000e1_ns::PublishMessage_Pair* temp = value_;
  value_ = NULL;
  return temp;
}
void PublishMessage::set_allocated_value(::chirp_000000e1_ns::PublishMessage_Pair* value) {
  delete value_;
  value_ = value;
  if (value) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:chirp_000000e1_ns.PublishMessage.value)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace chirp_000000e1_ns

// @@protoc_insertion_point(global_scope)
