// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: yogi_001ad001.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "yogi_001ad001.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/io/zero_copy_stream_impl_lite.h>
// @@protoc_insertion_point(includes)

namespace yogi_001ad001_ns {

void protobuf_ShutdownFile_yogi_5f001ad001_2eproto() {
  delete ScatterMessage::default_instance_;
  delete ScatterMessage_Pair::default_instance_;
  delete GatherMessage::default_instance_;
  delete PublishMessage::default_instance_;
  delete MasterMessage::default_instance_;
  delete MasterMessage_Pair::default_instance_;
  delete SlaveMessage::default_instance_;
}

#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
void protobuf_AddDesc_yogi_5f001ad001_2eproto_impl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#else
void protobuf_AddDesc_yogi_5f001ad001_2eproto() GOOGLE_ATTRIBUTE_COLD;
void protobuf_AddDesc_yogi_5f001ad001_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#endif
  ScatterMessage::default_instance_ = new ScatterMessage();
  ScatterMessage_Pair::default_instance_ = new ScatterMessage_Pair();
  GatherMessage::default_instance_ = new GatherMessage();
  PublishMessage::default_instance_ = new PublishMessage();
  MasterMessage::default_instance_ = new MasterMessage();
  MasterMessage_Pair::default_instance_ = new MasterMessage_Pair();
  SlaveMessage::default_instance_ = new SlaveMessage();
  ScatterMessage::default_instance_->InitAsDefaultInstance();
  ScatterMessage_Pair::default_instance_->InitAsDefaultInstance();
  GatherMessage::default_instance_->InitAsDefaultInstance();
  PublishMessage::default_instance_->InitAsDefaultInstance();
  MasterMessage::default_instance_->InitAsDefaultInstance();
  MasterMessage_Pair::default_instance_->InitAsDefaultInstance();
  SlaveMessage::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_yogi_5f001ad001_2eproto);
}

#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AddDesc_yogi_5f001ad001_2eproto_once_);
void protobuf_AddDesc_yogi_5f001ad001_2eproto() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AddDesc_yogi_5f001ad001_2eproto_once_,
                 &protobuf_AddDesc_yogi_5f001ad001_2eproto_impl);
}
#else
// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_yogi_5f001ad001_2eproto {
  StaticDescriptorInitializer_yogi_5f001ad001_2eproto() {
    protobuf_AddDesc_yogi_5f001ad001_2eproto();
  }
} static_descriptor_initializer_yogi_5f001ad001_2eproto_;
#endif

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int ScatterMessage_Pair::kFirstFieldNumber;
const int ScatterMessage_Pair::kSecondFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

ScatterMessage_Pair::ScatterMessage_Pair()
  : ::google::protobuf::MessageLite(), _arena_ptr_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:yogi_001ad001_ns.ScatterMessage.Pair)
}

void ScatterMessage_Pair::InitAsDefaultInstance() {
  _is_default_instance_ = true;
}

ScatterMessage_Pair::ScatterMessage_Pair(const ScatterMessage_Pair& from)
  : ::google::protobuf::MessageLite(),
    _arena_ptr_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:yogi_001ad001_ns.ScatterMessage.Pair)
}

void ScatterMessage_Pair::SharedCtor() {
    _is_default_instance_ = false;
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  first_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  second_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

ScatterMessage_Pair::~ScatterMessage_Pair() {
  // @@protoc_insertion_point(destructor:yogi_001ad001_ns.ScatterMessage.Pair)
  SharedDtor();
}

void ScatterMessage_Pair::SharedDtor() {
  first_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  second_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  if (this != &default_instance()) {
  #else
  if (this != default_instance_) {
  #endif
  }
}

void ScatterMessage_Pair::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ScatterMessage_Pair& ScatterMessage_Pair::default_instance() {
#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  protobuf_AddDesc_yogi_5f001ad001_2eproto();
#else
  if (default_instance_ == NULL) protobuf_AddDesc_yogi_5f001ad001_2eproto();
#endif
  return *default_instance_;
}

ScatterMessage_Pair* ScatterMessage_Pair::default_instance_ = NULL;

ScatterMessage_Pair* ScatterMessage_Pair::New(::google::protobuf::Arena* arena) const {
  ScatterMessage_Pair* n = new ScatterMessage_Pair;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void ScatterMessage_Pair::Clear() {
// @@protoc_insertion_point(message_clear_start:yogi_001ad001_ns.ScatterMessage.Pair)
  first_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  second_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

bool ScatterMessage_Pair::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:yogi_001ad001_ns.ScatterMessage.Pair)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional string first = 1;
      case 1: {
        if (tag == 10) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_first()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->first().data(), this->first().length(),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "yogi_001ad001.ScatterMessage.Pair.first"));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_second;
        break;
      }

      // optional string second = 2;
      case 2: {
        if (tag == 18) {
         parse_second:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_second()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->second().data(), this->second().length(),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "yogi_001ad001.ScatterMessage.Pair.second"));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:yogi_001ad001_ns.ScatterMessage.Pair)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:yogi_001ad001_ns.ScatterMessage.Pair)
  return false;
#undef DO_
}

void ScatterMessage_Pair::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:yogi_001ad001_ns.ScatterMessage.Pair)
  // optional string first = 1;
  if (this->first().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->first().data(), this->first().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "yogi_001ad001.ScatterMessage.Pair.first");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->first(), output);
  }

  // optional string second = 2;
  if (this->second().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->second().data(), this->second().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "yogi_001ad001.ScatterMessage.Pair.second");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->second(), output);
  }

  // @@protoc_insertion_point(serialize_end:yogi_001ad001_ns.ScatterMessage.Pair)
}

int ScatterMessage_Pair::ByteSize() const {
// @@protoc_insertion_point(message_byte_size_start:yogi_001ad001_ns.ScatterMessage.Pair)
  int total_size = 0;

  // optional string first = 1;
  if (this->first().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->first());
  }

  // optional string second = 2;
  if (this->second().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->second());
  }

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void ScatterMessage_Pair::CheckTypeAndMergeFrom(
    const ::google::protobuf::MessageLite& from) {
  MergeFrom(*::google::protobuf::down_cast<const ScatterMessage_Pair*>(&from));
}

void ScatterMessage_Pair::MergeFrom(const ScatterMessage_Pair& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:yogi_001ad001_ns.ScatterMessage.Pair)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  if (from.first().size() > 0) {

    first_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.first_);
  }
  if (from.second().size() > 0) {

    second_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.second_);
  }
}

void ScatterMessage_Pair::CopyFrom(const ScatterMessage_Pair& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:yogi_001ad001_ns.ScatterMessage.Pair)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ScatterMessage_Pair::IsInitialized() const {

  return true;
}

void ScatterMessage_Pair::Swap(ScatterMessage_Pair* other) {
  if (other == this) return;
  InternalSwap(other);
}
void ScatterMessage_Pair::InternalSwap(ScatterMessage_Pair* other) {
  first_.Swap(&other->first_);
  second_.Swap(&other->second_);
  _unknown_fields_.Swap(&other->_unknown_fields_);
  std::swap(_cached_size_, other->_cached_size_);
}

::std::string ScatterMessage_Pair::GetTypeName() const {
  return "yogi_001ad001.ScatterMessage.Pair";
}


// -------------------------------------------------------------------

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int ScatterMessage::kValueFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

ScatterMessage::ScatterMessage()
  : ::google::protobuf::MessageLite(), _arena_ptr_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:yogi_001ad001_ns.ScatterMessage)
}

void ScatterMessage::InitAsDefaultInstance() {
  _is_default_instance_ = true;
#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  value_ = const_cast< ::yogi_001ad001_ns::ScatterMessage_Pair*>(
      ::yogi_001ad001_ns::ScatterMessage_Pair::internal_default_instance());
#else
  value_ = const_cast< ::yogi_001ad001_ns::ScatterMessage_Pair*>(&::yogi_001ad001_ns::ScatterMessage_Pair::default_instance());
#endif
}

ScatterMessage::ScatterMessage(const ScatterMessage& from)
  : ::google::protobuf::MessageLite(),
    _arena_ptr_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:yogi_001ad001_ns.ScatterMessage)
}

void ScatterMessage::SharedCtor() {
    _is_default_instance_ = false;
  _cached_size_ = 0;
  value_ = NULL;
}

ScatterMessage::~ScatterMessage() {
  // @@protoc_insertion_point(destructor:yogi_001ad001_ns.ScatterMessage)
  SharedDtor();
}

void ScatterMessage::SharedDtor() {
  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  if (this != &default_instance()) {
  #else
  if (this != default_instance_) {
  #endif
    delete value_;
  }
}

void ScatterMessage::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ScatterMessage& ScatterMessage::default_instance() {
#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  protobuf_AddDesc_yogi_5f001ad001_2eproto();
#else
  if (default_instance_ == NULL) protobuf_AddDesc_yogi_5f001ad001_2eproto();
#endif
  return *default_instance_;
}

ScatterMessage* ScatterMessage::default_instance_ = NULL;

ScatterMessage* ScatterMessage::New(::google::protobuf::Arena* arena) const {
  ScatterMessage* n = new ScatterMessage;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void ScatterMessage::Clear() {
// @@protoc_insertion_point(message_clear_start:yogi_001ad001_ns.ScatterMessage)
  if (GetArenaNoVirtual() == NULL && value_ != NULL) delete value_;
  value_ = NULL;
}

bool ScatterMessage::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:yogi_001ad001_ns.ScatterMessage)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional .yogi_001ad001.ScatterMessage.Pair value = 2;
      case 2: {
        if (tag == 18) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_value()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:yogi_001ad001_ns.ScatterMessage)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:yogi_001ad001_ns.ScatterMessage)
  return false;
#undef DO_
}

void ScatterMessage::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:yogi_001ad001_ns.ScatterMessage)
  // optional .yogi_001ad001.ScatterMessage.Pair value = 2;
  if (this->has_value()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessage(
      2, *this->value_, output);
  }

  // @@protoc_insertion_point(serialize_end:yogi_001ad001_ns.ScatterMessage)
}

int ScatterMessage::ByteSize() const {
// @@protoc_insertion_point(message_byte_size_start:yogi_001ad001_ns.ScatterMessage)
  int total_size = 0;

  // optional .yogi_001ad001.ScatterMessage.Pair value = 2;
  if (this->has_value()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        *this->value_);
  }

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void ScatterMessage::CheckTypeAndMergeFrom(
    const ::google::protobuf::MessageLite& from) {
  MergeFrom(*::google::protobuf::down_cast<const ScatterMessage*>(&from));
}

void ScatterMessage::MergeFrom(const ScatterMessage& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:yogi_001ad001_ns.ScatterMessage)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  if (from.has_value()) {
    mutable_value()->::yogi_001ad001_ns::ScatterMessage_Pair::MergeFrom(from.value());
  }
}

void ScatterMessage::CopyFrom(const ScatterMessage& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:yogi_001ad001_ns.ScatterMessage)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ScatterMessage::IsInitialized() const {

  return true;
}

void ScatterMessage::Swap(ScatterMessage* other) {
  if (other == this) return;
  InternalSwap(other);
}
void ScatterMessage::InternalSwap(ScatterMessage* other) {
  std::swap(value_, other->value_);
  _unknown_fields_.Swap(&other->_unknown_fields_);
  std::swap(_cached_size_, other->_cached_size_);
}

::std::string ScatterMessage::GetTypeName() const {
  return "yogi_001ad001.ScatterMessage";
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// ScatterMessage_Pair

// optional string first = 1;
void ScatterMessage_Pair::clear_first() {
  first_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 const ::std::string& ScatterMessage_Pair::first() const {
  // @@protoc_insertion_point(field_get:yogi_001ad001_ns.ScatterMessage.Pair.first)
  return first_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void ScatterMessage_Pair::set_first(const ::std::string& value) {
  
  first_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:yogi_001ad001_ns.ScatterMessage.Pair.first)
}
 void ScatterMessage_Pair::set_first(const char* value) {
  
  first_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:yogi_001ad001_ns.ScatterMessage.Pair.first)
}
 void ScatterMessage_Pair::set_first(const char* value, size_t size) {
  
  first_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:yogi_001ad001_ns.ScatterMessage.Pair.first)
}
 ::std::string* ScatterMessage_Pair::mutable_first() {
  
  // @@protoc_insertion_point(field_mutable:yogi_001ad001_ns.ScatterMessage.Pair.first)
  return first_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 ::std::string* ScatterMessage_Pair::release_first() {
  // @@protoc_insertion_point(field_release:yogi_001ad001_ns.ScatterMessage.Pair.first)
  
  return first_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void ScatterMessage_Pair::set_allocated_first(::std::string* first) {
  if (first != NULL) {
    
  } else {
    
  }
  first_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), first);
  // @@protoc_insertion_point(field_set_allocated:yogi_001ad001_ns.ScatterMessage.Pair.first)
}

// optional string second = 2;
void ScatterMessage_Pair::clear_second() {
  second_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 const ::std::string& ScatterMessage_Pair::second() const {
  // @@protoc_insertion_point(field_get:yogi_001ad001_ns.ScatterMessage.Pair.second)
  return second_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void ScatterMessage_Pair::set_second(const ::std::string& value) {
  
  second_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:yogi_001ad001_ns.ScatterMessage.Pair.second)
}
 void ScatterMessage_Pair::set_second(const char* value) {
  
  second_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:yogi_001ad001_ns.ScatterMessage.Pair.second)
}
 void ScatterMessage_Pair::set_second(const char* value, size_t size) {
  
  second_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:yogi_001ad001_ns.ScatterMessage.Pair.second)
}
 ::std::string* ScatterMessage_Pair::mutable_second() {
  
  // @@protoc_insertion_point(field_mutable:yogi_001ad001_ns.ScatterMessage.Pair.second)
  return second_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 ::std::string* ScatterMessage_Pair::release_second() {
  // @@protoc_insertion_point(field_release:yogi_001ad001_ns.ScatterMessage.Pair.second)
  
  return second_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void ScatterMessage_Pair::set_allocated_second(::std::string* second) {
  if (second != NULL) {
    
  } else {
    
  }
  second_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), second);
  // @@protoc_insertion_point(field_set_allocated:yogi_001ad001_ns.ScatterMessage.Pair.second)
}

// -------------------------------------------------------------------

// ScatterMessage

// optional .yogi_001ad001.ScatterMessage.Pair value = 2;
bool ScatterMessage::has_value() const {
  return !_is_default_instance_ && value_ != NULL;
}
void ScatterMessage::clear_value() {
  if (GetArenaNoVirtual() == NULL && value_ != NULL) delete value_;
  value_ = NULL;
}
const ::yogi_001ad001_ns::ScatterMessage_Pair& ScatterMessage::value() const {
  // @@protoc_insertion_point(field_get:yogi_001ad001_ns.ScatterMessage.value)
#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  return value_ != NULL ? *value_ : *default_instance().value_;
#else
  return value_ != NULL ? *value_ : *default_instance_->value_;
#endif
}
::yogi_001ad001_ns::ScatterMessage_Pair* ScatterMessage::mutable_value() {
  
  if (value_ == NULL) {
    value_ = new ::yogi_001ad001_ns::ScatterMessage_Pair;
  }
  // @@protoc_insertion_point(field_mutable:yogi_001ad001_ns.ScatterMessage.value)
  return value_;
}
::yogi_001ad001_ns::ScatterMessage_Pair* ScatterMessage::release_value() {
  // @@protoc_insertion_point(field_release:yogi_001ad001_ns.ScatterMessage.value)
  
  ::yogi_001ad001_ns::ScatterMessage_Pair* temp = value_;
  value_ = NULL;
  return temp;
}
void ScatterMessage::set_allocated_value(::yogi_001ad001_ns::ScatterMessage_Pair* value) {
  delete value_;
  value_ = value;
  if (value) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:yogi_001ad001_ns.ScatterMessage.value)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int GatherMessage::kValueFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

GatherMessage::GatherMessage()
  : ::google::protobuf::MessageLite(), _arena_ptr_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:yogi_001ad001_ns.GatherMessage)
}

void GatherMessage::InitAsDefaultInstance() {
  _is_default_instance_ = true;
}

GatherMessage::GatherMessage(const GatherMessage& from)
  : ::google::protobuf::MessageLite(),
    _arena_ptr_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:yogi_001ad001_ns.GatherMessage)
}

void GatherMessage::SharedCtor() {
    _is_default_instance_ = false;
  _cached_size_ = 0;
  value_ = false;
}

GatherMessage::~GatherMessage() {
  // @@protoc_insertion_point(destructor:yogi_001ad001_ns.GatherMessage)
  SharedDtor();
}

void GatherMessage::SharedDtor() {
  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  if (this != &default_instance()) {
  #else
  if (this != default_instance_) {
  #endif
  }
}

void GatherMessage::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const GatherMessage& GatherMessage::default_instance() {
#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  protobuf_AddDesc_yogi_5f001ad001_2eproto();
#else
  if (default_instance_ == NULL) protobuf_AddDesc_yogi_5f001ad001_2eproto();
#endif
  return *default_instance_;
}

GatherMessage* GatherMessage::default_instance_ = NULL;

GatherMessage* GatherMessage::New(::google::protobuf::Arena* arena) const {
  GatherMessage* n = new GatherMessage;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void GatherMessage::Clear() {
// @@protoc_insertion_point(message_clear_start:yogi_001ad001_ns.GatherMessage)
  value_ = false;
}

bool GatherMessage::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:yogi_001ad001_ns.GatherMessage)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional bool value = 2;
      case 2: {
        if (tag == 16) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &value_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:yogi_001ad001_ns.GatherMessage)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:yogi_001ad001_ns.GatherMessage)
  return false;
#undef DO_
}

void GatherMessage::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:yogi_001ad001_ns.GatherMessage)
  // optional bool value = 2;
  if (this->value() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(2, this->value(), output);
  }

  // @@protoc_insertion_point(serialize_end:yogi_001ad001_ns.GatherMessage)
}

int GatherMessage::ByteSize() const {
// @@protoc_insertion_point(message_byte_size_start:yogi_001ad001_ns.GatherMessage)
  int total_size = 0;

  // optional bool value = 2;
  if (this->value() != 0) {
    total_size += 1 + 1;
  }

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void GatherMessage::CheckTypeAndMergeFrom(
    const ::google::protobuf::MessageLite& from) {
  MergeFrom(*::google::protobuf::down_cast<const GatherMessage*>(&from));
}

void GatherMessage::MergeFrom(const GatherMessage& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:yogi_001ad001_ns.GatherMessage)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  if (from.value() != 0) {
    set_value(from.value());
  }
}

void GatherMessage::CopyFrom(const GatherMessage& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:yogi_001ad001_ns.GatherMessage)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool GatherMessage::IsInitialized() const {

  return true;
}

void GatherMessage::Swap(GatherMessage* other) {
  if (other == this) return;
  InternalSwap(other);
}
void GatherMessage::InternalSwap(GatherMessage* other) {
  std::swap(value_, other->value_);
  _unknown_fields_.Swap(&other->_unknown_fields_);
  std::swap(_cached_size_, other->_cached_size_);
}

::std::string GatherMessage::GetTypeName() const {
  return "yogi_001ad001.GatherMessage";
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// GatherMessage

// optional bool value = 2;
void GatherMessage::clear_value() {
  value_ = false;
}
 bool GatherMessage::value() const {
  // @@protoc_insertion_point(field_get:yogi_001ad001_ns.GatherMessage.value)
  return value_;
}
 void GatherMessage::set_value(bool value) {
  
  value_ = value;
  // @@protoc_insertion_point(field_set:yogi_001ad001_ns.GatherMessage.value)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int PublishMessage::kValueFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

PublishMessage::PublishMessage()
  : ::google::protobuf::MessageLite(), _arena_ptr_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:yogi_001ad001_ns.PublishMessage)
}

void PublishMessage::InitAsDefaultInstance() {
  _is_default_instance_ = true;
}

PublishMessage::PublishMessage(const PublishMessage& from)
  : ::google::protobuf::MessageLite(),
    _arena_ptr_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:yogi_001ad001_ns.PublishMessage)
}

void PublishMessage::SharedCtor() {
    _is_default_instance_ = false;
  _cached_size_ = 0;
  value_ = false;
}

PublishMessage::~PublishMessage() {
  // @@protoc_insertion_point(destructor:yogi_001ad001_ns.PublishMessage)
  SharedDtor();
}

void PublishMessage::SharedDtor() {
  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  if (this != &default_instance()) {
  #else
  if (this != default_instance_) {
  #endif
  }
}

void PublishMessage::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const PublishMessage& PublishMessage::default_instance() {
#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  protobuf_AddDesc_yogi_5f001ad001_2eproto();
#else
  if (default_instance_ == NULL) protobuf_AddDesc_yogi_5f001ad001_2eproto();
#endif
  return *default_instance_;
}

PublishMessage* PublishMessage::default_instance_ = NULL;

PublishMessage* PublishMessage::New(::google::protobuf::Arena* arena) const {
  PublishMessage* n = new PublishMessage;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void PublishMessage::Clear() {
// @@protoc_insertion_point(message_clear_start:yogi_001ad001_ns.PublishMessage)
  value_ = false;
}

bool PublishMessage::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:yogi_001ad001_ns.PublishMessage)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional bool value = 2;
      case 2: {
        if (tag == 16) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &value_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:yogi_001ad001_ns.PublishMessage)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:yogi_001ad001_ns.PublishMessage)
  return false;
#undef DO_
}

void PublishMessage::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:yogi_001ad001_ns.PublishMessage)
  // optional bool value = 2;
  if (this->value() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(2, this->value(), output);
  }

  // @@protoc_insertion_point(serialize_end:yogi_001ad001_ns.PublishMessage)
}

int PublishMessage::ByteSize() const {
// @@protoc_insertion_point(message_byte_size_start:yogi_001ad001_ns.PublishMessage)
  int total_size = 0;

  // optional bool value = 2;
  if (this->value() != 0) {
    total_size += 1 + 1;
  }

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void PublishMessage::CheckTypeAndMergeFrom(
    const ::google::protobuf::MessageLite& from) {
  MergeFrom(*::google::protobuf::down_cast<const PublishMessage*>(&from));
}

void PublishMessage::MergeFrom(const PublishMessage& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:yogi_001ad001_ns.PublishMessage)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  if (from.value() != 0) {
    set_value(from.value());
  }
}

void PublishMessage::CopyFrom(const PublishMessage& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:yogi_001ad001_ns.PublishMessage)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool PublishMessage::IsInitialized() const {

  return true;
}

void PublishMessage::Swap(PublishMessage* other) {
  if (other == this) return;
  InternalSwap(other);
}
void PublishMessage::InternalSwap(PublishMessage* other) {
  std::swap(value_, other->value_);
  _unknown_fields_.Swap(&other->_unknown_fields_);
  std::swap(_cached_size_, other->_cached_size_);
}

::std::string PublishMessage::GetTypeName() const {
  return "yogi_001ad001.PublishMessage";
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// PublishMessage

// optional bool value = 2;
void PublishMessage::clear_value() {
  value_ = false;
}
 bool PublishMessage::value() const {
  // @@protoc_insertion_point(field_get:yogi_001ad001_ns.PublishMessage.value)
  return value_;
}
 void PublishMessage::set_value(bool value) {
  
  value_ = value;
  // @@protoc_insertion_point(field_set:yogi_001ad001_ns.PublishMessage.value)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int MasterMessage_Pair::kFirstFieldNumber;
const int MasterMessage_Pair::kSecondFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

MasterMessage_Pair::MasterMessage_Pair()
  : ::google::protobuf::MessageLite(), _arena_ptr_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:yogi_001ad001_ns.MasterMessage.Pair)
}

void MasterMessage_Pair::InitAsDefaultInstance() {
  _is_default_instance_ = true;
}

MasterMessage_Pair::MasterMessage_Pair(const MasterMessage_Pair& from)
  : ::google::protobuf::MessageLite(),
    _arena_ptr_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:yogi_001ad001_ns.MasterMessage.Pair)
}

void MasterMessage_Pair::SharedCtor() {
    _is_default_instance_ = false;
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  first_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  second_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

MasterMessage_Pair::~MasterMessage_Pair() {
  // @@protoc_insertion_point(destructor:yogi_001ad001_ns.MasterMessage.Pair)
  SharedDtor();
}

void MasterMessage_Pair::SharedDtor() {
  first_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  second_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  if (this != &default_instance()) {
  #else
  if (this != default_instance_) {
  #endif
  }
}

void MasterMessage_Pair::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const MasterMessage_Pair& MasterMessage_Pair::default_instance() {
#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  protobuf_AddDesc_yogi_5f001ad001_2eproto();
#else
  if (default_instance_ == NULL) protobuf_AddDesc_yogi_5f001ad001_2eproto();
#endif
  return *default_instance_;
}

MasterMessage_Pair* MasterMessage_Pair::default_instance_ = NULL;

MasterMessage_Pair* MasterMessage_Pair::New(::google::protobuf::Arena* arena) const {
  MasterMessage_Pair* n = new MasterMessage_Pair;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void MasterMessage_Pair::Clear() {
// @@protoc_insertion_point(message_clear_start:yogi_001ad001_ns.MasterMessage.Pair)
  first_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  second_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

bool MasterMessage_Pair::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:yogi_001ad001_ns.MasterMessage.Pair)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional string first = 1;
      case 1: {
        if (tag == 10) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_first()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->first().data(), this->first().length(),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "yogi_001ad001.MasterMessage.Pair.first"));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_second;
        break;
      }

      // optional string second = 2;
      case 2: {
        if (tag == 18) {
         parse_second:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_second()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->second().data(), this->second().length(),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "yogi_001ad001.MasterMessage.Pair.second"));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:yogi_001ad001_ns.MasterMessage.Pair)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:yogi_001ad001_ns.MasterMessage.Pair)
  return false;
#undef DO_
}

void MasterMessage_Pair::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:yogi_001ad001_ns.MasterMessage.Pair)
  // optional string first = 1;
  if (this->first().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->first().data(), this->first().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "yogi_001ad001.MasterMessage.Pair.first");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->first(), output);
  }

  // optional string second = 2;
  if (this->second().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->second().data(), this->second().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "yogi_001ad001.MasterMessage.Pair.second");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->second(), output);
  }

  // @@protoc_insertion_point(serialize_end:yogi_001ad001_ns.MasterMessage.Pair)
}

int MasterMessage_Pair::ByteSize() const {
// @@protoc_insertion_point(message_byte_size_start:yogi_001ad001_ns.MasterMessage.Pair)
  int total_size = 0;

  // optional string first = 1;
  if (this->first().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->first());
  }

  // optional string second = 2;
  if (this->second().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->second());
  }

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void MasterMessage_Pair::CheckTypeAndMergeFrom(
    const ::google::protobuf::MessageLite& from) {
  MergeFrom(*::google::protobuf::down_cast<const MasterMessage_Pair*>(&from));
}

void MasterMessage_Pair::MergeFrom(const MasterMessage_Pair& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:yogi_001ad001_ns.MasterMessage.Pair)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  if (from.first().size() > 0) {

    first_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.first_);
  }
  if (from.second().size() > 0) {

    second_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.second_);
  }
}

void MasterMessage_Pair::CopyFrom(const MasterMessage_Pair& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:yogi_001ad001_ns.MasterMessage.Pair)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool MasterMessage_Pair::IsInitialized() const {

  return true;
}

void MasterMessage_Pair::Swap(MasterMessage_Pair* other) {
  if (other == this) return;
  InternalSwap(other);
}
void MasterMessage_Pair::InternalSwap(MasterMessage_Pair* other) {
  first_.Swap(&other->first_);
  second_.Swap(&other->second_);
  _unknown_fields_.Swap(&other->_unknown_fields_);
  std::swap(_cached_size_, other->_cached_size_);
}

::std::string MasterMessage_Pair::GetTypeName() const {
  return "yogi_001ad001.MasterMessage.Pair";
}


// -------------------------------------------------------------------

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int MasterMessage::kValueFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

MasterMessage::MasterMessage()
  : ::google::protobuf::MessageLite(), _arena_ptr_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:yogi_001ad001_ns.MasterMessage)
}

void MasterMessage::InitAsDefaultInstance() {
  _is_default_instance_ = true;
#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  value_ = const_cast< ::yogi_001ad001_ns::MasterMessage_Pair*>(
      ::yogi_001ad001_ns::MasterMessage_Pair::internal_default_instance());
#else
  value_ = const_cast< ::yogi_001ad001_ns::MasterMessage_Pair*>(&::yogi_001ad001_ns::MasterMessage_Pair::default_instance());
#endif
}

MasterMessage::MasterMessage(const MasterMessage& from)
  : ::google::protobuf::MessageLite(),
    _arena_ptr_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:yogi_001ad001_ns.MasterMessage)
}

void MasterMessage::SharedCtor() {
    _is_default_instance_ = false;
  _cached_size_ = 0;
  value_ = NULL;
}

MasterMessage::~MasterMessage() {
  // @@protoc_insertion_point(destructor:yogi_001ad001_ns.MasterMessage)
  SharedDtor();
}

void MasterMessage::SharedDtor() {
  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  if (this != &default_instance()) {
  #else
  if (this != default_instance_) {
  #endif
    delete value_;
  }
}

void MasterMessage::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const MasterMessage& MasterMessage::default_instance() {
#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  protobuf_AddDesc_yogi_5f001ad001_2eproto();
#else
  if (default_instance_ == NULL) protobuf_AddDesc_yogi_5f001ad001_2eproto();
#endif
  return *default_instance_;
}

MasterMessage* MasterMessage::default_instance_ = NULL;

MasterMessage* MasterMessage::New(::google::protobuf::Arena* arena) const {
  MasterMessage* n = new MasterMessage;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void MasterMessage::Clear() {
// @@protoc_insertion_point(message_clear_start:yogi_001ad001_ns.MasterMessage)
  if (GetArenaNoVirtual() == NULL && value_ != NULL) delete value_;
  value_ = NULL;
}

bool MasterMessage::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:yogi_001ad001_ns.MasterMessage)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional .yogi_001ad001.MasterMessage.Pair value = 2;
      case 2: {
        if (tag == 18) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_value()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:yogi_001ad001_ns.MasterMessage)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:yogi_001ad001_ns.MasterMessage)
  return false;
#undef DO_
}

void MasterMessage::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:yogi_001ad001_ns.MasterMessage)
  // optional .yogi_001ad001.MasterMessage.Pair value = 2;
  if (this->has_value()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessage(
      2, *this->value_, output);
  }

  // @@protoc_insertion_point(serialize_end:yogi_001ad001_ns.MasterMessage)
}

int MasterMessage::ByteSize() const {
// @@protoc_insertion_point(message_byte_size_start:yogi_001ad001_ns.MasterMessage)
  int total_size = 0;

  // optional .yogi_001ad001.MasterMessage.Pair value = 2;
  if (this->has_value()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        *this->value_);
  }

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void MasterMessage::CheckTypeAndMergeFrom(
    const ::google::protobuf::MessageLite& from) {
  MergeFrom(*::google::protobuf::down_cast<const MasterMessage*>(&from));
}

void MasterMessage::MergeFrom(const MasterMessage& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:yogi_001ad001_ns.MasterMessage)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  if (from.has_value()) {
    mutable_value()->::yogi_001ad001_ns::MasterMessage_Pair::MergeFrom(from.value());
  }
}

void MasterMessage::CopyFrom(const MasterMessage& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:yogi_001ad001_ns.MasterMessage)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool MasterMessage::IsInitialized() const {

  return true;
}

void MasterMessage::Swap(MasterMessage* other) {
  if (other == this) return;
  InternalSwap(other);
}
void MasterMessage::InternalSwap(MasterMessage* other) {
  std::swap(value_, other->value_);
  _unknown_fields_.Swap(&other->_unknown_fields_);
  std::swap(_cached_size_, other->_cached_size_);
}

::std::string MasterMessage::GetTypeName() const {
  return "yogi_001ad001.MasterMessage";
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// MasterMessage_Pair

// optional string first = 1;
void MasterMessage_Pair::clear_first() {
  first_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 const ::std::string& MasterMessage_Pair::first() const {
  // @@protoc_insertion_point(field_get:yogi_001ad001_ns.MasterMessage.Pair.first)
  return first_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void MasterMessage_Pair::set_first(const ::std::string& value) {
  
  first_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:yogi_001ad001_ns.MasterMessage.Pair.first)
}
 void MasterMessage_Pair::set_first(const char* value) {
  
  first_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:yogi_001ad001_ns.MasterMessage.Pair.first)
}
 void MasterMessage_Pair::set_first(const char* value, size_t size) {
  
  first_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:yogi_001ad001_ns.MasterMessage.Pair.first)
}
 ::std::string* MasterMessage_Pair::mutable_first() {
  
  // @@protoc_insertion_point(field_mutable:yogi_001ad001_ns.MasterMessage.Pair.first)
  return first_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 ::std::string* MasterMessage_Pair::release_first() {
  // @@protoc_insertion_point(field_release:yogi_001ad001_ns.MasterMessage.Pair.first)
  
  return first_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void MasterMessage_Pair::set_allocated_first(::std::string* first) {
  if (first != NULL) {
    
  } else {
    
  }
  first_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), first);
  // @@protoc_insertion_point(field_set_allocated:yogi_001ad001_ns.MasterMessage.Pair.first)
}

// optional string second = 2;
void MasterMessage_Pair::clear_second() {
  second_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 const ::std::string& MasterMessage_Pair::second() const {
  // @@protoc_insertion_point(field_get:yogi_001ad001_ns.MasterMessage.Pair.second)
  return second_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void MasterMessage_Pair::set_second(const ::std::string& value) {
  
  second_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:yogi_001ad001_ns.MasterMessage.Pair.second)
}
 void MasterMessage_Pair::set_second(const char* value) {
  
  second_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:yogi_001ad001_ns.MasterMessage.Pair.second)
}
 void MasterMessage_Pair::set_second(const char* value, size_t size) {
  
  second_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:yogi_001ad001_ns.MasterMessage.Pair.second)
}
 ::std::string* MasterMessage_Pair::mutable_second() {
  
  // @@protoc_insertion_point(field_mutable:yogi_001ad001_ns.MasterMessage.Pair.second)
  return second_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 ::std::string* MasterMessage_Pair::release_second() {
  // @@protoc_insertion_point(field_release:yogi_001ad001_ns.MasterMessage.Pair.second)
  
  return second_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void MasterMessage_Pair::set_allocated_second(::std::string* second) {
  if (second != NULL) {
    
  } else {
    
  }
  second_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), second);
  // @@protoc_insertion_point(field_set_allocated:yogi_001ad001_ns.MasterMessage.Pair.second)
}

// -------------------------------------------------------------------

// MasterMessage

// optional .yogi_001ad001.MasterMessage.Pair value = 2;
bool MasterMessage::has_value() const {
  return !_is_default_instance_ && value_ != NULL;
}
void MasterMessage::clear_value() {
  if (GetArenaNoVirtual() == NULL && value_ != NULL) delete value_;
  value_ = NULL;
}
const ::yogi_001ad001_ns::MasterMessage_Pair& MasterMessage::value() const {
  // @@protoc_insertion_point(field_get:yogi_001ad001_ns.MasterMessage.value)
#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  return value_ != NULL ? *value_ : *default_instance().value_;
#else
  return value_ != NULL ? *value_ : *default_instance_->value_;
#endif
}
::yogi_001ad001_ns::MasterMessage_Pair* MasterMessage::mutable_value() {
  
  if (value_ == NULL) {
    value_ = new ::yogi_001ad001_ns::MasterMessage_Pair;
  }
  // @@protoc_insertion_point(field_mutable:yogi_001ad001_ns.MasterMessage.value)
  return value_;
}
::yogi_001ad001_ns::MasterMessage_Pair* MasterMessage::release_value() {
  // @@protoc_insertion_point(field_release:yogi_001ad001_ns.MasterMessage.value)
  
  ::yogi_001ad001_ns::MasterMessage_Pair* temp = value_;
  value_ = NULL;
  return temp;
}
void MasterMessage::set_allocated_value(::yogi_001ad001_ns::MasterMessage_Pair* value) {
  delete value_;
  value_ = value;
  if (value) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:yogi_001ad001_ns.MasterMessage.value)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int SlaveMessage::kValueFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

SlaveMessage::SlaveMessage()
  : ::google::protobuf::MessageLite(), _arena_ptr_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:yogi_001ad001_ns.SlaveMessage)
}

void SlaveMessage::InitAsDefaultInstance() {
  _is_default_instance_ = true;
}

SlaveMessage::SlaveMessage(const SlaveMessage& from)
  : ::google::protobuf::MessageLite(),
    _arena_ptr_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:yogi_001ad001_ns.SlaveMessage)
}

void SlaveMessage::SharedCtor() {
    _is_default_instance_ = false;
  _cached_size_ = 0;
  value_ = false;
}

SlaveMessage::~SlaveMessage() {
  // @@protoc_insertion_point(destructor:yogi_001ad001_ns.SlaveMessage)
  SharedDtor();
}

void SlaveMessage::SharedDtor() {
  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  if (this != &default_instance()) {
  #else
  if (this != default_instance_) {
  #endif
  }
}

void SlaveMessage::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const SlaveMessage& SlaveMessage::default_instance() {
#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  protobuf_AddDesc_yogi_5f001ad001_2eproto();
#else
  if (default_instance_ == NULL) protobuf_AddDesc_yogi_5f001ad001_2eproto();
#endif
  return *default_instance_;
}

SlaveMessage* SlaveMessage::default_instance_ = NULL;

SlaveMessage* SlaveMessage::New(::google::protobuf::Arena* arena) const {
  SlaveMessage* n = new SlaveMessage;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void SlaveMessage::Clear() {
// @@protoc_insertion_point(message_clear_start:yogi_001ad001_ns.SlaveMessage)
  value_ = false;
}

bool SlaveMessage::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:yogi_001ad001_ns.SlaveMessage)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional bool value = 2;
      case 2: {
        if (tag == 16) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &value_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:yogi_001ad001_ns.SlaveMessage)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:yogi_001ad001_ns.SlaveMessage)
  return false;
#undef DO_
}

void SlaveMessage::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:yogi_001ad001_ns.SlaveMessage)
  // optional bool value = 2;
  if (this->value() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(2, this->value(), output);
  }

  // @@protoc_insertion_point(serialize_end:yogi_001ad001_ns.SlaveMessage)
}

int SlaveMessage::ByteSize() const {
// @@protoc_insertion_point(message_byte_size_start:yogi_001ad001_ns.SlaveMessage)
  int total_size = 0;

  // optional bool value = 2;
  if (this->value() != 0) {
    total_size += 1 + 1;
  }

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void SlaveMessage::CheckTypeAndMergeFrom(
    const ::google::protobuf::MessageLite& from) {
  MergeFrom(*::google::protobuf::down_cast<const SlaveMessage*>(&from));
}

void SlaveMessage::MergeFrom(const SlaveMessage& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:yogi_001ad001_ns.SlaveMessage)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  if (from.value() != 0) {
    set_value(from.value());
  }
}

void SlaveMessage::CopyFrom(const SlaveMessage& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:yogi_001ad001_ns.SlaveMessage)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SlaveMessage::IsInitialized() const {

  return true;
}

void SlaveMessage::Swap(SlaveMessage* other) {
  if (other == this) return;
  InternalSwap(other);
}
void SlaveMessage::InternalSwap(SlaveMessage* other) {
  std::swap(value_, other->value_);
  _unknown_fields_.Swap(&other->_unknown_fields_);
  std::swap(_cached_size_, other->_cached_size_);
}

::std::string SlaveMessage::GetTypeName() const {
  return "yogi_001ad001.SlaveMessage";
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// SlaveMessage

// optional bool value = 2;
void SlaveMessage::clear_value() {
  value_ = false;
}
 bool SlaveMessage::value() const {
  // @@protoc_insertion_point(field_get:yogi_001ad001_ns.SlaveMessage.value)
  return value_;
}
 void SlaveMessage::set_value(bool value) {
  
  value_ = value;
  // @@protoc_insertion_point(field_set:yogi_001ad001_ns.SlaveMessage.value)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace yogi_001ad001_ns

// @@protoc_insertion_point(global_scope)
